export default {
	SCROLL_INTERVAL: 1_600,
	IDLE_COUNTER_ALLOWANCE: 2,
	BLOCK_DELAY_IN_MINUTES: 1,
	BLOCK_PERIOD_IN_MINUTES: 1,
	BRAND_COLOR: "#e1285c",
	BRAND_COLOR_DARK: "#be2a54",
	BLOCKS_PER_MINUTE: 6,
	BLOCKS_PER_MINUTE_MIN: 0,
	BLOCKS_PER_MINUTE_MAX: 60,
	BLOCKS_PER_MINUTE_DANGER_ZONE: 29,
	SCROLLS_PER_MINUTE_MIN: 10,
	SCROLLS_PER_MINUTE_MAX: 200,
	SCROLLS_PER_MINUTE_DANGER_ZONE: 80,
	DEFAULT_PROFILE_IMG: {
		normal: "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
		mini: "https://abs.twimg.com/sticky/default_profile_images/default_profile_mini.png",
	},
	DEQUEUE_BATCH_SIZE: 42,
	TEMP_QUEUE_BATCH_THRESHOLD: 14,
	BLOCKS_PER_SESSION_LIMIT: 500,
	USAGE_URL: "https://dmstern.github.io/likers-blocker/#usage",
	RELEASE_NOTES_URL: "https://github.com/dmstern/likers-blocker/releases",
};
