export default {
	SCROLL_INTERVAL: 1_600,
	IDLE_COUNTER_ALLOWANCE: 2,
	BLOCK_DELAY_IN_MINUTES: 1,
	BLOCK_PERIOD_IN_MINUTES: 1,
	BRAND_COLOR: "#e1285c",
	BRAND_COLOR_DARK: "#be2a54",
	BLOCKS_PER_MINUTE: 6,
};
