name: CI	# Name of your workflow

on:
  workflow_dispatch:	# Allows you to manually trigger workflow
  push:
    # Triggers workflow only if code is pushed to master/main branch
    branches: [ master, main ]

jobs:
  Publish:
    name: Publish Package to Chrome and Edge
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Build
      run: |
        npm run build
        npm run postversion
    name: Publish Chrome
    runs-on: ubuntu-latest

    steps:
    - name: Upload & release Chrome
      uses: mnao305/chrome-extension-upload@v4.0.1
      with:
        file-path: likers-blocker_chromium.zip
        extension-id: melnbpmfhaejmcpfflfjmchondkpmkcj
        client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
        client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
    - name: Upload & release Edge
      run: |
        touch .env
        echo EDGEclientId=${{ secrets.EDGEclientId }} >> .env
        echo EDGEclientSecret=${{ secrets.EDGEclientSecret }} >> .env
        echo EDGEaccessTokenUrl==${{ secrets.EDGEaccessTokenUrl }} >> .env
        npm run publish_edge

    